// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNTs1o3K0y4rjMXHjbC-gp4WQUJfyyMj8',
    appId: '1:627102778647:web:866b41131cf3a889a8e352',
    messagingSenderId: '627102778647',
    projectId: 'wheelwiz-38bc0',
    authDomain: 'wheelwiz-38bc0.firebaseapp.com',
    storageBucket: 'wheelwiz-38bc0.appspot.com',
    measurementId: 'G-6CQJHW099K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqR8rQpR9HgpX5u1k37uCritVBj9upB5o',
    appId: '1:627102778647:android:a174485354903702a8e352',
    messagingSenderId: '627102778647',
    projectId: 'wheelwiz-38bc0',
    storageBucket: 'wheelwiz-38bc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADICEoSWH1vMj2Exf-kQhmpLm6kq-S7Ag',
    appId: '1:627102778647:ios:f54776250cbba974a8e352',
    messagingSenderId: '627102778647',
    projectId: 'wheelwiz-38bc0',
    storageBucket: 'wheelwiz-38bc0.appspot.com',
    iosBundleId: 'com.example.innowah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADICEoSWH1vMj2Exf-kQhmpLm6kq-S7Ag',
    appId: '1:627102778647:ios:f54776250cbba974a8e352',
    messagingSenderId: '627102778647',
    projectId: 'wheelwiz-38bc0',
    storageBucket: 'wheelwiz-38bc0.appspot.com',
    iosBundleId: 'com.example.innowah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNTs1o3K0y4rjMXHjbC-gp4WQUJfyyMj8',
    appId: '1:627102778647:web:81df99dd603295a9a8e352',
    messagingSenderId: '627102778647',
    projectId: 'wheelwiz-38bc0',
    authDomain: 'wheelwiz-38bc0.firebaseapp.com',
    storageBucket: 'wheelwiz-38bc0.appspot.com',
    measurementId: 'G-YW64YSL3C3',
  );
}
